### PR TITLE
Use Eigen3 in CMake file to prevent doSPA from crashing

### PR DESCRIPTION
**Pull request by varunagrawal**
Fix for #18.

### CODE REVIEW

**Comment by varunagrawal** [comment]
@mikeferguson any updates on this?

**Review by elias-hanna — APPROVED** [review]
This fixed the issue for me. Thank you.

**Comment by fljlk** [comment]
I am using Ros Melodic and the catkin crashed for me.

What solved it was adding the c++11 line from the CMake file, and adding -fpermissive right after it.

**Comment by varunagrawal** [comment]
Any updates on this?

**Comment by elias-hanna** [comment]
I used the fork of slam_karto from @nkuwenjian and it totally fixed the issue for me. Some people still had a problem like the one described by @fljlk but his solution fixed that issue too.

**Comment by varunagrawal** [comment]
@elias-hanna that unfortunately does not answer my question. I had already looked at @nkuwenjian's repo and proposed this fix based on my understanding of the bug. I was hoping to have this PR merged so that this bug is fixed permanently.

**Comment by mikeferguson** [comment]
Indigo is long since dead (we can't release new things because the buildfarm is gone) - but I just made this change to Melodic - since we were getting warnings on the build farm (cmake_modules is deprecated) - https://github.com/ros-perception/slam_karto/commit/6a126514bce53e632e9db3cf50d1319cf9e3e332

**Pull request closed without merging**
